### PR TITLE
update to python 3

### PR DESCRIPTION
**Pull request by kobbled**
update to python 3

### CODE REVIEW

**Review by gavanderhoorn — COMMENTED** [review]
Same comment about the Python launcher as in https://github.com/gavanderhoorn/ktransw_py/pull/17.

**Comment by gavanderhoorn** [comment]
Nice to see not a lot of changes were needed for Python 3 compatibility.

**Comment by kobbled** [comment]
I reverted the cmd file back to the upstream master as per gavanderhoorn/ktransw_py#17.

**Comment by gavanderhoorn** [comment]
@kobbled: I've added some commits clarifying that both Python 2 *and* 3 should work for `rossum`.

**Comment by gavanderhoorn** [comment]
Thanks for the PR @kobbled :+1: 

Much appreciated.

**Pull request merged**
